#
#spring.datasource.url=jdbc:postgresql://dpg-d9bc1m3eo5us73ecbbdg-a.oregon-postgres.render.com/havkdb
#spring.datasource.username=havkdb_user
#spring.datasource.password=0WN4S9iMHWx2AR7ucFxMwpqIskIth5ji
#spring.datasource.driver-class-name=org.postgresql.Driver


#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/online
spring.datasource.url=jdbc:h2:mem:d75f2545-7c53-40e7-a84f-83888d5426d9
spring.datasource.username=sa
spring.datasource.password=



spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# EXIBIÇÃO DE QUERIES NO CONSOLE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
