# CONFIGURAÇÃO DO BANCO DE DADOS (POSTGRESQL)
# Use a linha abaixo se estiver rodando o Spring localmente na sua máquina:
spring.datasource.url=jdbc:postgresql://dpg-d9bc1m3eo5us73ecbbdg-a.oregon-postgres.render.com/havkdb
# Descomente a linha abaixo (e comente a de cima) apenas se o Spring rodar dentro do próprio Render:
# spring.datasource.url=jdbc:postgresql://dpg-d9bc1m3eo5us73ecbbdg-a:5432/havkdb




spring.datasource.username=havkdb_user
spring.datasource.password=0WN4S9iMHWx2AR7ucFxMwpqIskIth5ji
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURAÇÃO DO JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop

# EXIBIÇÃO DE QUERIES NO CONSOLE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
